### ISSUE TITLE
Pathmode: where?

### ISSUE THREAD

**Issue by epaga** [gamendegamer321/Commlines#1]
So this is probably me just being blind, but where in the settings can you turn on path mode? would be helpful to be more specific in the readme.

P.S. LOVE this mod. Thanks!

**Comment by epaga** [comment]
A bit more info...I found this in the main menu mod settings dialog:

![image](https://github.com/gamendegamer321/Commlines/assets/58567/54068cb9-ce07-4a20-8dc2-5df6abcf3b2d)

But clicking that "all" button does nothing... is this where it should be able to be changed?

**Comment by gamendegamer321** [comment]
Within the games settings menu, there should be a "mods" tab. Within this tab there is a section for CommLines, here you can change the mode.

![image](https://github.com/gamendegamer321/Commlines/assets/74590966/a09220d0-6d77-470c-996c-6b504f2a0d48)
